### ISSUE TITLE
Install command needs to be done inside the Node-Red directory

### ISSUE THREAD

**Issue by Gun-neR** [node-red-contrib-themes/theme-collection#10]
# Problem/Motivation - No resultant dark mode

> (Why the issue was filed) - Install didn't have desired results (AKA nothing changed)

- Theme version: Normal
- Node-RED version:  2.0.5
- Platform/OS:  RPi Buster
- Browser:  Chrome

## Proposed changes

As per Node-Red Forum - https://discourse.nodered.org/t/dark-mode-theme-looking-rather-pale/49768

```
knolleary

You have run the install in the wrong directory.

You need to be in ~/.node-red
```

**Comment by bonanitech** [comment]
That's right. See https://nodered.org/docs/user-guide/runtime/adding-nodes#installing-with-npm

**Comment by Gun-neR** [comment]
Sorry, I guess I meant that this tidbit could be added to your own install instructions... for the uninitiated who, as far as I can recall at least, ran every other npm install command from home directory.... unless stated otherwise in the directions :)

**Comment by bonanitech** [comment]
I understand. But, since there are so many different ways for people to install Node-RED, it's almost impossible to cover them all in the installation instructions.

**Comment by Gun-neR** [comment]
As I now understand it, regardless of method of NR install... installing an npm contrib, that needs to effect NR, requires it to be done in the NR directory.

Whether you add that detail or not is really no longer meaningful, as anyone running into same issue may look for and see this topic.
