### ISSUE TITLE
Please remove or rename Solarized Dark Grey theme

### ISSUE THREAD

**Issue by ristomatti** [node-red-contrib-themes/theme-collection#125]
I was under the impression we were in the process of discussing including the theme in the collection. I've replied to you at Node-RED forum asking not to archive the repository and explaining the reasoning why I would be ok if it was not included in the collection while I would have liked it to be found under the @node-red-contrib-themes org. Now I see the repository archived and no more have access to remove the notice and point the possible few users of the theme back to my personal GitHub repository where I apparently will be maintaining the theme in future.

As I explained in my reply, this is one way to keep my CSS skills up-to-date but I need to be able to maintain the creative freedom to include the "unorthodox" customizations required to make the theme look like it does on the screenshots I've posted at https://discourse.nodered.org/t/announce-node-red-contrib-themes-solarized-dark-grey/29504, even if it means it cannot then be included in the official theme pack.

**Comment by bonanitech** [comment]
As per your request, I will remove the theme from the collection.

**Comment by bonanitech** [comment]
And if you want, I can transfer ownership of the repository to you.

**Comment by ristomatti** [comment]
Thank you!

**Comment by ristomatti** [comment]
I still have my own version at https://github.com/ristomatti/node-red-contrib-theme-solarized-dark-grey. Thanks anyway!
