### ISSUE TITLE
Steam Punk Theme

### ISSUE THREAD

**Issue by dinogregorich** [node-red-contrib-themes/theme-collection#205]
### Details

I have been a software engineer for over 30 years.  But I have always loved the artistic nature of Steam Punk.

While working with Node-RED the other day, I had the idea that with the 'wires' and objects, what if they were in shapes of steam punk machines and the wires were various piping?  Then I thought that working with Node-RED with such a theme would encourage young people into programming and software development, since building functions and apps would be not only functional, but artistic and cool creations.

We could take it even farther by various animations when running in debug mode...electric arcs, steam puffs, spinning things and flashing lights.

**Comment by bonanitech** [comment]
It's a great idea, but I don't think I have the skills to create a theme like this.
