### ISSUE TITLE
Dark and Midnight-Red themes do not play well with Mermaid markdown in node description

### ISSUE THREAD

**Issue by colinl** [node-red-contrib-themes/theme-collection#292]
### Describe the problem

Using the dark or midnight-red themes with a mermaid diagram in the node description, the diagram shown in the Information panel for the node is not ideal.
For the exported node below it appears, in midnight-red as
![image](https://github.com/node-red-contrib-themes/theme-collection/assets/38307/2ef5bd94-c706-49c9-99cc-593a2683ac7c)
In the dark theme it is similarly shown.
For reference, in Obsidian it appears as
![image](https://github.com/node-red-contrib-themes/theme-collection/assets/38307/d9d0d83e-a9dc-4ebe-94a9-faf2025d20d5)

### Steps To Reproduce

1. Ensure node-red version 3.1.0-beta.4 or above is installed
2. Import the flow (node) below
3. With dark or midnight-red theme enabled select the imported node and view the Information tab in right hand pane

```
[{"id":"55d54d1c275c150f","type":"function","z":"bdd7be38.d3b55","name":"Test mermaid markdown","func":"\nreturn msg;","outputs":1,"timeout":0,"noerr":0,"initialize":"","finalize":"","libs":[],"x":810,"y":60,"wires":[[]],"info":"```mermaid\nstateDiagram-v2\nState_1 --> State_2: Transition 1\nState_2 --> State_3: Another transition\nState_3 --> State_1: Back to \\nthe start\n```"}]
```

### Expected Behavior

The diagram should be displayed more clearly

### Theme Collection version

3.0.6

### Node-RED version

3.1.0-beta.4

### Platform/O.S.

Ubuntu 22.04

### Browser(s)

Edge (Firefox is similar)

**Comment by bonanitech** [comment]
The upstream issue was closed. The fix will be included in the next release.
