### ISSUE TITLE
colours all messed up (sorry)

### ISSUE THREAD

**Issue by Just-another-pleb** [node-red-contrib-themes/theme-collection#310]
### Describe the problem

![Screenshot from 2023-09-12 19-28-59](https://github.com/node-red-contrib-themes/theme-collection/assets/39888280/ba86987c-7e3c-4f4a-a5e1-e05ef3e570e2)

I don't know what happened to cause this.

Back story:
Things were working - afaik - quite happily.
I opened a `function` node and the background colour was WHITE.
I tried a few others and they were the same.
Strange as I have worked on this machine recently and not seen this problem.

I have recently installed the theme on another machine and remembered the *new* way to do it.
So I went through the motions of checking.   the `settings.js` file didn't look right.
So I checked the pallet manager and the theme wasn't shown.

Installed it edited the theme and restarted.
Oh the pain.  (Sorry)
Same.

I have 3 4 machines running NR all with NR 3.0.2 (or 3.0.1 maybe) and they were all working happily.
Now it is confusing to me.
I've installed the node on 3 of them and now it is the `dashboard` list is messed up.
`function` nodes are fine.

Please help.

### Steps To Reproduce

There are no errors listed/shown.

### Node-RED version

3.0.2

### Platform/O.S.

Buster

### Browser(s)

Firefox

**Comment by bonanitech** [comment]
It looks like it did not recognize CSS variables.

What version of Dashboard do you have installed?

Theme support was introduced in version 3.2.0.

**Comment by Just-another-pleb** [comment]
2.26   3.16 fail.
3.5 working.
3.17 working.

So 3.16 to 3.17 could be a problem.
Argh.   Ok, I'll update them and get back to you.
Very sorry.   But thanks.

**Comment by Just-another-pleb** [comment]
You are the best.

I am stupid.

Didn't keep up to date with things.

I guess I am glad it is/was nothing else/serious.
