### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by michaelblight** [node-red-contrib-themes/theme-collection#342]
### Describe the problem

I would have like to first create this under discussions, but I don't seem to have access. I don't see a "create discussion" button. When I go there from the link I get "You can't perform that action at this time.". Moving on...

I cannot install this add-on. If I do so from the Node Red palette it says it failed and the log only shows this:
```
-----------------------------------------------------------
2023-11-23T04:34:36.560Z Install : @node-red-contrib-themes/theme-collection 3.1.5
```

I'm running under docker with tag 3.1, and it has node v18.17.1. When I made the host the same version and installed with npm I get:
```
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "@node-red-contrib-themes" of package "@node-red-contrib-themes": Tags may not have any characters that encodeURIComponent encodes.
```
I'm running the npm install in the same folder that has "node_modules" - I assume that is the correct location.

Note sure what to do next.

### Expected Behavior

It installs.

### Node-RED version

v3.1.0

### Platform/O.S.

Ubuntu

### Browser(s)

Chrome

**Comment by michaelblight** [comment]
I also have Node Red as a Home Assistant add-on, and installing the module there works fine.

**Comment by bonanitech** [comment]
> I'm running under docker with tag 3.1

Which docker image did you use to create the container? And how are you running it?

> I'm running the npm install in the same folder that has "node_modules"

Is that the same directory that has the `settings.js` file?

> I also have Node Red as a Home Assistant add-on, and installing the module there works fine.

This theme collection is already part of the Home Assistant add-on. You don't need to install it. See https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md#option-theme

**Comment by michaelblight** [comment]
I suspect I just don't know what to expect. With a default theme, is this how it should look now? I've made the group dark green for clarity:

<img width="184" alt="image" src="https://github.com/node-red-contrib-themes/theme-collection/assets/373079/6d2734c6-0297-42ee-bfa3-194d84afa98b">

If that's how it looks now, that's fine and just my misunderstanding. It's a bit confusing when NR has virtually no screenshots.

I'm running the container with this:
```
sudo docker rm -f -v node-red-ha
sudo docker run -it \
        --restart=always \
        --dns=192.168.0.61 \
        -p 1888:1880 \
        -e TZ="Australia/Melbourne" \
        -e LANG=en_US.UTF-8 \
        -e LANGUAGE=en_US:en \
        -e LC_ALL=en_US.UTF-8 \
        -v /etc/localtime:/etc/localtime \
        -v /data/docker/node-red-ha/data:/data \
        -v /data/docker/node-red-ha/data/shared:/shared \
        -v /mnt/remote/ha:/ha \
        -v /data/docker/log:/log \
        --name node-red-ha \
        nodered/node-red
```
So it's the official NR docker image from [github](https://hub.docker.com/r/nodered/node-red). And yes, I'm doing the npm install in the same folder as "settings.js" which mapped to "/data" within the container.

Initially I was doing it on the host, not from within the container. So I then used Portainer to connect to the container and uninstalled/re-installed from the "/data" folder and restarted the container (ran the script above). I don't get the error then, but I'm still getting a white background on the status text. This might highlight the problem - I'm specifying "dark" theme but the canvas in NR is not dark. The other settings (like title) are being picked up though.

The relevant section of "settings.js" I have is:
```
    editorTheme: {
        projects: {
            // To enable the Projects feature, set this value to true
            enabled: false
        },
        page: {
                title: "Home Assistant"
        },
        header: {
                title: "Node-RED Home Assistant",
        },
        editorTheme: {
                theme: "dark"
        },
        codeEditor: {
                lib: "monaco"
        }
```

**Comment by bonanitech** [comment]
That should be

```
    editorTheme: {
        projects: {
            // To enable the Projects feature, set this value to true
            enabled: false
        },
        page: {
                title: "Home Assistant"
        },
        header: {
                title: "Node-RED Home Assistant",
        },
        theme: "dark",
        codeEditor: {
                lib: "monaco"
        }
```

See https://nodered.org/docs/user-guide/runtime/configuration#editor-themes and https://github.com/node-red/node-red/blob/master/packages/node_modules/node-red/settings.js#L375-L380.

**Comment by michaelblight** [comment]
Ah yes now the status text is on a black background. I've probably had the code like that for over 5 years without realising. So the status text is now meant to look like that. On the NR forum steve-mcl said it should have a "semi-opaque background", but it appears to be fully-opaque. Hence my confusion.

After uninstalling and re-installing I no longer get an error when trying to install via the UI (assuming I uninstall prior).

However it's very confusing that if you install themes via the palette, even if it works, it doesn't show up in the list and it still shows "install" afterwards as if it didn't work. Although if you try to install again it says "already loaded".

**Comment by bonanitech** [comment]
> I would have like to first create this under discussions, but I don't seem to have access.

@michaelblight, thanks for the heads up. I just fixed an issue that was preventing users from creating new discussions.
