### ISSUE TITLE
please add a teal accent 

### ISSUE THREAD

**Issue by zkollz** [node-red-contrib-themes/theme-collection#449]
### Details

cyan/turquoise accent #1D817F

**Comment by bonanitech** [comment]
Do you have links/screenshots of themes using that color to be used as a reference?

**Comment by zkollz** [comment]
> Do you have links/screenshots of themes using that color to be used as a reference?

I've seen a version very similar to solarized dark in a yt video but the color was more like turquoise than dark, and it looked great!

![IMG_20240621_180854.png](https://github.com/node-red-contrib-themes/theme-collection/assets/97865793/112d109c-a07b-47f6-8ca9-e3b4a5a720e5)

It was something like that what I saw

**Comment by bonanitech** [comment]
> I've seen a version very similar to solarized dark in a yt video but the color was more like turquoise than dark, and it looked great!

What video?

**Comment by bonanitech** [comment]
Something like this?

<img width="1920" alt="image" src="https://github.com/node-red-contrib-themes/theme-collection/assets/29807944/b1f1068b-dd32-4c70-b299-e93b85c1399f">

**Comment by zkollz** [comment]
Actually I was referring to something a little more light blue and less green, I don't know if that's possible this is the hex color code: 
#008080

**Comment by bonanitech** [comment]
Sorry for the delay. It's not exactly the color you mentioned, but it's very close. I hope you like it.

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/08972a4c-b90d-4423-9c9e-1b181d30b885">

**Comment by zkollz** [comment]
> Sorry for the delay. It's not exactly the color you mentioned, but it's very close. I hope you like it.
> 
> <img width="1920" alt="image" src="https://github.com/user-attachments/assets/08972a4c-b90d-4423-9c9e-1b181d30b885">

Is there an ETA for this new color?

**Comment by zkollz** [comment]
> Sorry for the delay. It's not exactly the color you mentioned, but it's very close. I hope you like it.
> 
> <img width="1920" alt="image" src="https://github.com/user-attachments/assets/08972a4c-b90d-4423-9c9e-1b181d30b885">

Is there an ETA for this new color?

**Comment by bonanitech** [comment]
It will be released alongside Node-RED v4.1.
