### ISSUE TITLE
Flow edit pane missing tab (cannot rename a flow tab) in Cobalt

### ISSUE THREAD

**Issue by SynoUser-NL** [node-red-contrib-themes/theme-collection#456]
### Describe the problem

Using NodeRED In Home Assistant. 
When selecting the Cobalt theme, it is not possible to edit Flow names (Properties screen missing).
When selecting another theme (Dark) the Properties appear again.

### Steps To Reproduce

https://github.com/hassio-addons/addon-node-red/issues/1906

### Expected Behavior

Changing theme should not disable or delete NodeRED functions or configurations.

### Node-RED version

4.0.3

### Platform/O.S.

Home Assistant

### Browser(s)

Firefox

**Comment by bonanitech** [comment]
Hey @SynoUser-NL! Thanks for reporting the issue.

I just released a new version with a fix.

**Comment by SynoUser-NL** [comment]
Wow! Thanks for fixing this so quickly!
